"""empty message

Revision ID: 983b7047c892
Revises: f4e2a94056f6
Create Date: 2021-09-22 13:07:50.428469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983b7047c892'
down_revision = 'f4e2a94056f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zodiac_lists', 'first_name_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('zodiac_lists', 'match_name_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zodiac_lists', 'match_name_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('zodiac_lists', 'first_name_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
