"""empty message

Revision ID: f4e2a94056f6
Revises: 0b110a1e78fe
Create Date: 2021-09-22 13:00:19.314148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e2a94056f6'
down_revision = '0b110a1e78fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zodiac_lists', 'match_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('zodiac_lists', 'match_name_sign',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zodiac_lists', 'match_name_sign',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('zodiac_lists', 'match_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###
