"""empty message

Revision ID: c5bdddeed993
Revises: 9500cf4edbfe
Create Date: 2021-09-21 23:55:23.695480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5bdddeed993'
down_revision = '9500cf4edbfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zodiac_lists', 'first_name_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('zodiac_lists', 'match_name_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zodiac_lists', 'match_name_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('zodiac_lists', 'first_name_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
