from .db import db
from .user import User
from .zodiac_list import ZodiacList
from .friends import Friend
from .friends_request import FriendRequest
from .horoscope_posts import HoroscopePost
from .comments import Comment
from .likes import Like
from .sun_signs import SunSign
from .compatibility import Compatibility
